# Generated by Django 5.2.3 on 2025-06-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('confirm', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'regist',
            },
        ),
    ]
