# Generated by Django 5.2.3 on 2025-06-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_logi'),
    ]

    operations = [
        migrations.CreateModel(
            name='subm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField()),
                ('message2', models.CharField()),
                ('rating', models.CharField()),
            ],
            options={
                'db_table': 'subm',
            },
        ),
    ]
