# Generated by Django 5.2.3 on 2025-06-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_booking_preferred_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='bokng',
        ),
        migrations.AlterModelTable(
            name='bokng',
            table='bokng',
        ),
    ]
