# Generated by Django 5.2.3 on 2025-06-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_booking_bokng_alter_bokng_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField()),
                ('preferred_time', models.IntegerField()),
                ('address', models.CharField()),
                ('landmark', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.DeleteModel(
            name='bokng',
        ),
    ]
