# Generated by Django 5.2.3 on 2025-06-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_booking_delete_bokng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='preferred_time',
        ),
    ]
