# Generated by Django 5.2.3 on 2025-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_bookng_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('EXP', models.DateField()),
                ('cvv', models.IntegerField()),
            ],
            options={
                'db_table': 'pay',
            },
        ),
        migrations.AlterField(
            model_name='bookng',
            name='preferred_time',
            field=models.DateTimeField(),
        ),
    ]
