# Generated by Django 5.2.3 on 2025-07-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_pay_alter_bookng_preferred_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subm',
            name='message2',
        ),
        migrations.RemoveField(
            model_name='subm',
            name='rating',
        ),
    ]
