# Generated by Django 5.2.3 on 2025-07-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_subm_message2_remove_subm_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logi',
        ),
    ]
